<a href="https://colab.research.google.com/github/mohitsbh/Ai_Learn_codes/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A=np.array([[2,3,5],[1,4,6]])
B=np.array([[1,2,3],[2,3,6]])

print("Addition of two Arrays A and B: \n",A+B)

Addition of two Arrays A and B: 
 [[ 3  5  8]
 [ 3  7 12]]


In [ ]:
print("Subtraction of two Arrays A and B: \n",A-B)

Subtraction of two Arrays A and B: 
 [[ 1  1  2]
 [-1  1  0]]


In [ ]:
C=2*A
print("Scalar Multiplication of Array A: \n",C)

Scalar Multiplication of Array A: 
 [[2 4]
 [6 8]]


In [ ]:
result=np.dot(A, B)
print("Multiplication of two Arrays A and B:\n", result)

Multiplication of two Arrays A and B:
 [[19 22]
 [43 50]]


In [ ]:
D=np.eye(4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
Z=np.zeros((2,6))
Z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
D=np.diag([2,3,4])
D

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [ ]:
import numpy as np
Array=([[2,3],[1,4]])
Determinant=np.linalg.det(Array)
Determinant

np.float64(5.000000000000001)

In [ ]:
np.linalg.inv(Array)

array([[ 0.8, -0.6],
       [-0.2,  0.4]])

In [ ]:
Eigval,Eigvect=np.linalg.eig(Array)
Eigval

array([1., 5.])

In [ ]:
Eigvect

array([[-0.9486833 , -0.70710678],
       [ 0.31622777, -0.70710678]])

In [ ]:
U,E,Vt=np.linalg.svd(Array)
U

array([[-0.65520174, -0.75545395],
       [-0.75545395,  0.65520174]])

In [ ]:
E

array([5.39834564, 0.92620968])

In [ ]:
Vt

array([[-0.38268343, -0.92387953],
       [-0.92387953,  0.38268343]])

In [ ]:
import numpy as np
A=np.array([[2,6],[3,5]])
A

array([[2, 6],
       [3, 5]])

In [ ]:
Determinant_A= np.linalg.det(A)
print("Determinant Of A is :\n",Determinant_A)

Determinant Of A is :
 -8.000000000000002


In [ ]:
Inverse_A=np.linalg.inv(A)
print("Inverse of A is:\n",Inverse_A)

Inverse of A is:
 [[-0.625  0.75 ]
 [ 0.375 -0.25 ]]


In [ ]:
Eigenvalues,Eigenvectors=np.linalg.eig(A)
print("Eigenvalues of A is:\n",Eigenvalues)
print("Eigenvectors of A is:\n",Eigenvectors)

Eigenvalues of A is:
 [-1.  8.]
Eigenvectors of A is:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [ ]:
U,E,Vt=np.linalg.svd(A)
print("Left orthogonal matrix is:\n",U)

Left orthogonal matrix is:
 [[-0.56357065 -0.65544846 -0.50276778]
 [-0.4887576  -0.22608959  0.84261468]
 [-0.66596106  0.72060448 -0.19293796]]


In [ ]:
print("Singular value of non-zeros of A is:\n",E)

Singular value of non-zeros of A is:
 [14.27104494  5.13169496  0.05461895]


In [ ]:
print("Right orthogonal matrix of A is:\n",Vt)

Right orthogonal matrix of A is:
 [[-0.55504713 -0.68817513 -0.46726616]
 [ 0.73575498 -0.14410674 -0.66173851]
 [-0.38805578  0.71108947 -0.58631432]]


In [ ]:
import numpy as np
A=np.array([[2,6,6],[3,5,4],[8,6,2]])
A

array([[2, 6, 6],
       [3, 5, 4],
       [8, 6, 2]])

In [ ]:
Determinant_A= np.linalg.det(A)
print("Determinant Of A is :\n",Determinant_A)

Determinant Of A is :
 -3.999999999999985


In [ ]:
Inverse_A=np.linalg.inv(A)
print("Inverse of A is:\n",Inverse_A)

Inverse of A is:
 [[ 3.5 -6.   1.5]
 [-6.5 11.  -2.5]
 [ 5.5 -9.   2. ]]


In [ ]:
Eigenvalues,Eigenvectors=np.linalg.eig(A)
print("Eigenvalues of A is:\n",Eigenvalues)
print("Eigenvectors of A is:\n",Eigenvectors)

Eigenvalues of A is:
 [13.77143698 -4.83155352  0.06011653]
Eigenvectors of A is:
 [[-0.58131988 -0.57302539  0.39146886]
 [-0.49375335 -0.15273682 -0.71087246]
 [-0.6467417   0.80517909  0.58430513]]


In [ ]:
Sigma=np.zeros([3,3])
np.fill_diagonal(Sigma,E)
Reconstruction= U @ Sigma @ Vt
print(Reconstruction)

[[2. 6. 6.]
 [3. 5. 4.]
 [8. 6. 2.]]


Assignment

In [ ]:
import numpy as np
from numpy.linalg import eig, svd, det
import matplotlib.pyplot as plt

# --- 1. Eigenvalues and Eigenvectors ---
# Define a 4x4 matrix
A = np.array([
    [4, 2, 2, 1],
    [0, 3, -1, 1],
    [0, 0, 2, 2],
    [0, 0, 0, 1]
])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues of A:")
print(eigenvalues)
print("\nEigenvectors of A (each column corresponds to one eigenvector):")
print(eigenvectors)

# --- 2. SVD for Dimensionality Reduction ---
# Create a synthetic dataset (e.g. 100 samples, 5 features)
np.random.seed(42)
X = np.random.rand(100, 5)

# Apply SVD
U, S, VT = svd(X, full_matrices=False)

# Keep top k=2 components
k = 2
X_reduced = U[:, :k] @ np.diag(S[:k])

print("\nReduced data shape using SVD (k=2):", X_reduced.shape)

# Optional: plot reduced 2D data
plt.scatter(X_reduced[:, 0], X_reduced[:, 1])
plt.title("2D Projection of Data via SVD")
plt.xlabel("Component 1")
plt.ylabel("Component 2")
plt.grid(True)
plt.show()

# --- 3. Verify Characteristic Polynomial det(A - λI) = 0 ---
# Pick one eigenvalue and plug into det(A - λI)
lambda_check = eigenvalues[0]
identity = np.eye(A.shape[0])
char_matrix = A - lambda_check * identity
det_result = det(char_matrix)

print(f"\nVerification of det(A - λI) = 0 for λ = {lambda_check:.4f}")
print(f"det(A - λI) = {det_result:.4e} (should be close to 0)")