<a href="https://colab.research.google.com/github/mohitsbh/Ai_Learn_codes/blob/main/Nnfs7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# ------------------- Input Dataset -------------------
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])   # Inputs
Y = np.array([[0], [0], [0], [1]])              # Target output for AND gate

# ------------------- Parameters -------------------
epochs = 10    # Number of iterations
alpha = 0.1    # Learning rate

nSamples, nFeatures = X.shape

# Add bias term (column of 1s)
Xb = np.hstack((np.ones((nSamples, 1)), X))  # Bias + input matrix
nSamples, nInputs = Xb.shape

# ------------------- Initialize Weights -------------------
weights_hebb = np.zeros((1, nInputs))   # Hebbian weights start from zero
weights_perceptron = np.random.rand(1, nInputs)  # Random initialization for Perceptron

# ------------------- Hebbian Learning Rule -------------------
for i in range(nSamples):
    weights_hebb = weights_hebb + Y[i] * Xb[i, :]

# ------------------- Perceptron Learning Rule -------------------
for epoch in range(epochs):
    for i in range(nSamples):
        net = weights_perceptron @ Xb[i, :].T   # Weighted sum
        out = (net >= 0).astype(int)            # Step activation (binary output)
        error = Y[i] - out                      # Error calculation
        weights_perceptron = weights_perceptron + alpha * error * Xb[i, :]

# ------------------- Testing After Training -------------------
outputs_hebb = (Xb @ weights_hebb.T) >= 0
outputs_perceptron = (Xb @ weights_perceptron.T) >= 0

# ------------------- Display Results -------------------
print("Final Hebbian Weights:")
print(weights_hebb)

print("Final Perceptron Weights:")
print(weights_perceptron)

print("Hebbian Output:")
print(outputs_hebb.astype(int))

print("Perceptron Output:")
print(outputs_perceptron.astype(int))

Final Hebbian Weights:
[[1. 1. 1.]]
Final Perceptron Weights:
[[-0.24187243  0.16464262  0.11447171]]
Hebbian Output:
[[1]
 [1]
 [1]
 [1]]
Perceptron Output:
[[0]
 [0]
 [0]
 [1]]
